services:
  python-app:
    image: my/python
    build: .
    container_name: python1
    ports: 
      - 8080:8080
    volumes: 
      - /mnt/d/CMPT 384/Assignment1:/usr/src/app
    command: "bash -c python3 -m http.server 8080"
    stdin_open: true
    tty: true